version: '3.9'

services:
  # サンプルなので1つのredis使い回します
  redis:
    image: "redis:latest"

  auth:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        SERVICE_NAME: auth
    image: goa-microservice/auth-service:latest
    ports:
      - "8090:8080"
    environment:
      - JWT_SECRET=secret
    restart: unless-stopped

  greet:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        SERVICE_NAME: greet
    ports:
      - "8091:8080"
    environment:
      - JWT_SECRET=secret
    restart: unless-stopped

  chat:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        SERVICE_NAME: chat
    ports:
      - "8092:8080"
    environment:
      - JWT_SECRET=secret
    restart: unless-stopped